# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perch < Formula
  desc "Minimal file viewer for coding agents"
  homepage "https://github.com/kateleext/perch"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kateleext/perch/releases/download/v0.3.0/perch_darwin_amd64.tar.gz"
      sha256 "c68dab1cd8699bb1f87841ec434f46dc4ad0a1a55302fd960b759f0471b5f09f"

      def install
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kateleext/perch/releases/download/v0.3.0/perch_darwin_arm64.tar.gz"
      sha256 "2d0038f98e1877aa5a23d0c2a91b90f5f65b646c58bf0ee2ee5248f38862856a"

      def install
        bin.install "perch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kateleext/perch/releases/download/v0.3.0/perch_linux_amd64.tar.gz"
      sha256 "0f85173e3fe210b585d89699330992c3a6ee21c826e1983a0f2ee72452c2b002"
      def install
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kateleext/perch/releases/download/v0.3.0/perch_linux_arm64.tar.gz"
      sha256 "7a390a780e423f87f8b3bfd2c0ab2fa591bc28a342d182198bdcdf9291fd3918"
      def install
        bin.install "perch"
      end
    end
  end

  test do
    system "#{bin}/perch --help" if File.exist?("#{bin}/perch")
  end
end
