# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perch < Formula
  desc "Minimal file viewer for coding agents"
  homepage "https://github.com/kateleext/perch"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kateleext/perch/releases/download/v0.0.1/perch_darwin_amd64.tar.gz"
      sha256 "72dfe32cc452deba2cf04b0bd0ec9d1825b04b4636140d1330d8a4f398615e75"

      def install
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kateleext/perch/releases/download/v0.0.1/perch_darwin_arm64.tar.gz"
      sha256 "bb2c6c3db1fd4d06af1ff68589aed27502bd12a43408950f28b3990c802de49f"

      def install
        bin.install "perch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kateleext/perch/releases/download/v0.0.1/perch_linux_amd64.tar.gz"
      sha256 "8dcc4fcd7710dbc46b9540a0227d7b6a4cfe2fcefc7fc7d14f21ca37860a3412"
      def install
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kateleext/perch/releases/download/v0.0.1/perch_linux_arm64.tar.gz"
      sha256 "a92c25fb4710ecccbc6bbf8b385b7dd365a6e9cd68f49db51a16663e4ac05a94"
      def install
        bin.install "perch"
      end
    end
  end
end
