# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perch < Formula
  desc "Passive file monitor for coding sessions"
  homepage "https://github.com/kateleext/perch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kateleext/perch/releases/download/v0.1.0/perch_darwin_amd64.tar.gz"
      sha256 "4b30f9f4a8f8f8b1696f9ae515eb1d861f3a4fd953601ca592d691c23fc2bbeb"

      def install
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kateleext/perch/releases/download/v0.1.0/perch_darwin_arm64.tar.gz"
      sha256 "56b275a8f04d28b3b467e7b7e23141aa8a0b5f1bd902bfc6d228cb6c4870af90"

      def install
        bin.install "perch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kateleext/perch/releases/download/v0.1.0/perch_linux_amd64.tar.gz"
      sha256 "e9dcf4fdf3f9509617d75ba6b11aa420c89f650de16d9b845083eedabf4caa32"
      def install
        bin.install "perch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kateleext/perch/releases/download/v0.1.0/perch_linux_arm64.tar.gz"
      sha256 "60fcc9439093be263be23c7167564f1f23e3f22ad6ed58c1af37634fde3343aa"
      def install
        bin.install "perch"
      end
    end
  end
end
